### ISSUE TITLE
Add UUIDs to events

### ISSUE THREAD

**Issue by WaldoAndFriends** [KK964/Minecraft_Websocket_Intergration#3]
**Is your feature request related to a problem? Please describe.**
When a player event is emitted, I'd like to have access to their UUID in addition to their username.

**Describe the solution you'd like**
Add the player's UUID as a property in the event.

**Describe alternatives you've considered**
I've considered calling an external API to retrieve the UUID of the player based on their name, but I could avoid this step if it was included in the event.

**Additional context**
The reason I'd like to have the UUIDs exposed is so that it would be trivial to call an 3rd party API like [Crafatar](https://crafatar.com) for example. To create an on stream alert for when a player joins the server.

**Comment by KK964** [comment]
I have been thinking of a way to integrate this into the current system.
Here are the ways that I think would be the best for developers using it:

1. Change from player name to an object like: `{name, uuid}`.
2. Add uuid to the returned array.


I personally think that changing to an object is the best way to go as it allows for future expansion without causing developers to rewrite. As this repo is still on the smaller side, I feel like doing larger changes is better earlier, rather than later. But as you are someone who has shown interest in the project, I would like to know what you think would be best.

**Comment by WaldoAndFriends** [comment]
I'd say change it into a player object since it's much more robust than adding it to the array, when it comes to future changes.
Also when it would be added to the array as a simple value, it's a bit weird that it wouldn't always be an adjecent value of the username, unless you change the order in the array for existing events. But in turn if you would change the order, why not make it an object from the start.

Currently you can still afford breaking changes.

**Comment by WaldoAndFriends** [comment]
To add the my previous comment, returning everything as an object instead of an array will make future extension to any event easier. Yes this is a breaking change now, but adding a single property afterwards should never result in a breaking change. 

Unless a single properly value would we replace by an object with more detail, but in that case the decision can always be made to keep both the single property value and a more advanced property that's an object with more information.

**Comment by KK964** [comment]
Implemented in Release [v1.0.2](https://github.com/KK964/Minecraft_Websocket_Intergration/releases/tag/v1.0.2)
