### ISSUE TITLE
Server not Reporting

### ISSUE THREAD

**Issue by AFAskar** [KK964/Minecraft_Websocket_Intergration#5]
**Describe the bug**
When connecting to the WS Server
Authentication not required...
Authentication needed... Send as "Bearer {Auth token}"
are not in The terminal window

**To Reproduce**

1. Host on an arm-64 platform
2. MC instance in a docker container
3. IDK just pulled those out of nowhere it just what makes my setup "Unique"

**Expected behavior**
Authentication not required...
Authentication needed... Send as "Bearer {Auth token}"
are sent to the terminal when connecting through streamer bot
**Screenshots**
1
![image](https://user-images.githubusercontent.com/68832286/205187765-9ce0dbeb-1bc8-4413-a1e5-a0096bcea305.png)
2
![image](https://user-images.githubusercontent.com/68832286/205187845-8a568f7c-d0cb-4ceb-a208-6ad84050602b.png)

**Additional context**

**Comment by KK964** [comment]
The messages `Authentication not required...` and `Authentication needed... Send as "Bearer {Auth token}"` are not supposed to show in the server terminal. These messages are sent from the Websocket Server to connecting clients. They are used so that incoming connecting clients can change their authentication method programmatically. 

I notice that you are setting up the connection using Streamer Bot, if you are using the [actions import from the Streamer Bot getting started wiki](https://github.com/KK964/Minecraft_Websocket_Intergration/wiki/StreamerBot), then you can ignore the messages entirely as it's already handled for you.
